//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedipolHastane
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mdplhasEntities : DbContext
    {
        public mdplhasEntities()
            : base("name=mdplhasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_dok> tbl_dok { get; set; }
        public virtual DbSet<tbl_hasta> tbl_hasta { get; set; }
        public virtual DbSet<tbl_blm> tbl_blm { get; set; }
    }
}
