//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedipolHastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blm
    {
        public int Id { get; set; }
        public string bolum { get; set; }
    }
}
